const OpenAI = require("openai");
const fs = require('fs');
require("dotenv").config();

// 1. Initialize Client
const openai = new OpenAI({
  baseURL: "https://openrouter.ai/api/v1",
  apiKey: process.env.OPENROUTER_API_KEY, 
  defaultHeaders: {
    "HTTP-Referer": "http://localhost:3000", 
    "X-Title": "AI News Aggregator",           
  }
});

// 2. The "Senior Journalist" System Prompt (Full Version)
const SYSTEM_PROMPT = `
You are a Senior Journalist analyzing high-signal AI news across the global ecosystem.
Your task is to identify developments that materially change how AI is built, governed, used, or experienced — not hype or speculation.

---

### IMPORTANCE DEFINITION
A news item is important if it produces at least one of the following:
- Measurable societal or labor change
- Economic or industry-wide effects
- Regulatory or legal precedent
- Shifts in power, access, or control of AI systems

Non-technical or incremental developments may still be highly important if their impact is real and durable.

---

### SCORING FRAMEWORK (0–100, WEIGHTED)
Evaluate each dimension independently.

**1. NOVELTY (30%)**  
Meaningful change in the current state.  
High: first-of-its-kind deployment, new model class, new law, or clear expansion.  
Low: repackaging, opinions, recycled narratives.

**2. IMPACT & SCALE (40%)**  
Size and durability of real-world consequences.  
High: affects industries, large populations, or governance structures.  
Low: localized or short-term effects.

**3. SUBSTANCE (20%)**  
Quality of verifiable detail.  
High: data, benchmarks, legal text, or primary reporting.  
Low: vague claims or promotional framing.

**4. TRUST & GROUNDING (10%)**  
Evidence and sourcing over brand reputation.  
High: official documentation or multiple confirmations.  
Low: single-source or unclear attribution.

---

### CATEGORY
Choose ONE: Research | Product | Industry | Economic/Labor | Policy | Society | Hardware

---

### SUMMARY RULES
Write exactly **3 bullet points**.

Each bullet should be **1–2 sentences**, written in a clear, neutral journalistic tone that invites reading without hype.
Bullets should:
- Describe what happened using concrete facts
- Explain why it matters or what it changes
- Add brief context or implications where helpful

Avoid marketing language, speculation, dramatic adjectives, or opinionated phrasing.
Do not sound conversational or robotic.

---

### OUTPUT FORMAT (JSON ONLY)
Return a valid JSON array. No markdown, no extra text.

[
  {
    "id": "original-uuid",
    "title": "Clear, factual, non-hype headline",
    "summary": [
      "Factual description of the development with necessary context.",
      "Primary impact or consequence for people, industry, or governance.",
      "Scope, limitation, or uncertainty that frames its significance."
    ],
    "category": "Policy",
    "curatorScore": 0-100,
    "confidence": 0-1,
    "reasoning": "One concise sentence explaining the main score tradeoff."
  }
]
`;

// 3. Mock Data: Stress Test (Mixture of High Signal & Noise)
const MOCK_ARTICLES = [
  {
    id: "hype-trap-1",
    title: "10 AI Tools That Will Replace Designers in 2026 - You Won't Believe #4!",
    content: "Design is dead! We found 10 new wrapper apps that use Stable Diffusion to generate logos instantly. Influencers say this is the end of Adobe. Click here to see why AI is taking over the creative industry immediately."
  },
  {
    id: "policy-signal-2",
    title: "US Copyright Office Reject's Artist's Appeal on Midjourney Images",
    content: "The US Copyright Office has issued a final decision in the case of 'Zarya of the Dawn', ruling that images generated by Midjourney are not eligible for copyright protection because they lack human authorship. The decision distinguishes between the human-written text (protected) and the AI visual output (public domain), setting a major legal precedent for generative AI IP rights."
  },
  {
    id: "tech-deep-3",
    title: "Google DeepMind releases Gemini 1.5 Pro Technical Report",
    content: "Google has published the technical report for Gemini 1.5 Pro. The model features a Mixture-of-Experts (MoE) architecture and a 10M token context window. In 'Needle-in-a-Haystack' tests, it achieved 99% recall across 1M tokens. The report also details new reinforcement learning techniques used to reduce hallucinations in code generation."
  }
];

async function runTest() {
  console.log("🚀 Starting AI Pipeline Test (Stress Test Mode)...");
  console.log("Using Model: tngtech/deepseek-r1t-chimera:free");

  try {
    const completion = await openai.chat.completions.create({
      model: "tngtech/deepseek-r1t-chimera:free", 
      messages: [
        { 
            role: "user", 
            content: SYSTEM_PROMPT + "\n\nDATA TO ANALYZE:\n" + JSON.stringify(MOCK_ARTICLES) 
        },
      ],
    });

    const rawOutput = completion.choices[0].message.content;
    console.log("\n✅ RAW AI OUTPUT:");
    console.log(rawOutput);

    // 2️⃣ Improved Parsing (Finds the FIRST array valid block)
    try {
      let jsonString = rawOutput.trim();
      // Find the first '['
      const start = jsonString.indexOf('[');
      // Find the last ']'
      const end = jsonString.lastIndexOf(']');
      
      if (start !== -1 && end !== -1) {
          jsonString = jsonString.substring(start, end + 1);
          const parsed = JSON.parse(jsonString);
          console.log("\n🎯 PARSED RESULTS:");
          console.log(JSON.stringify(parsed, null, 2));
          fs.writeFileSync('test_data.json', JSON.stringify(parsed, null, 2));
      } else {
          throw new Error("No JSON array found in output");
      }
    } catch(e) {
      console.error("❌ Final JSON Parse Error:", e.message);
    }

  } catch (error) {
    console.error("\n❌ FAILED:");
    console.error(error.message);
  }
}

runTest();

