const OpenAI = require("openai");
const fs = require('fs');
require("dotenv").config();

// 1. Initialize Client
const openai = new OpenAI({
  baseURL: "https://openrouter.ai/api/v1",
  apiKey: process.env.OPENROUTER_API_KEY, 
  defaultHeaders: {
    "HTTP-Referer": "http://localhost:3000", 
    "X-Title": "AI News Aggregator",           
  }
});

// 2. The "Senior Journalist" System Prompt (Full Version)
const SYSTEM_PROMPT = `
You are a Senior Journalist analyzing high-signal AI news globally.
Your task is to identify truly important AI developments — not hype.

---

### IMPORTANCE RULES
News is important if it creates:
- Societal or labor change
- Economic or industry-wide effects
- Regulatory or legal precedent
- Shifts in power, access, or control of AI

Importance may emerge from slow, cumulative change.
Do NOT penalize news for being non-technical or incremental.

---

### SCORING (0–100, weighted)

1. NOVELTY (30%)
Meaningful change in state, scale, or scope.
High: new model, law, use case, or expansion to new populations.
Low: routine opinions or recycled hype.

2. IMPACT & SCALE (40%)
Durable consequences across:
- Industry or markets
- Workers, creators, or consumers
- Governance or public trust
Single anecdotes may score higher if they signal emerging patterns.

3. SUBSTANCE (20%)
Evidence quality:
High: data, benchmarks, legal text, primary sources.
Low: vague, promotional, or unsourced claims.

4. TRUSTWORTHINESS (10%)
Evaluate grounding:
evidence > brand reputation.
Consider sourcing, verification, and corroboration.

---

### CATEGORY RULE
Choose ONE category based on primary impact:
Research | Product | Industry | Economic/Labor | Policy | Society | Hardware

If uncertain, prioritize:
Policy > Economic/Labor > Society > Industry > Product > Research > Hardware

---

### OUTPUT (JSON ONLY)
Return a valid JSON Array containing one object for each analyzed article.
[
  {
    "id": "Use the ID provided in the input",
    "title": "Clear, direct, non-hype headline",
    "summary": ["Bullet 1", "Bullet 2", "Bullet 3"],
    "context": "Optional: one short sentence or brief paragraph ONLY if needed for nuance.",
    "category": "Research | Product | Industry | Economic/Labor | Policy | Society | Hardware",
    "curatorScore": 0,
    "confidence": 0.0,
    "reasoning": "One sentence explaining the main score tradeoffs."
  }
]
`;

// 3. Mock Data: Stress Test (Mixture of High Signal & Noise)
const MOCK_ARTICLES = [
  {
    id: "hype-trap-1",
    title: "10 AI Tools That Will Replace Designers in 2026 - You Won't Believe #4!",
    content: "Design is dead! We found 10 new wrapper apps that use Stable Diffusion to generate logos instantly. Influencers say this is the end of Adobe. Click here to see why AI is taking over the creative industry immediately."
  },
  {
    id: "policy-signal-2",
    title: "US Copyright Office Reject's Artist's Appeal on Midjourney Images",
    content: "The US Copyright Office has issued a final decision in the case of 'Zarya of the Dawn', ruling that images generated by Midjourney are not eligible for copyright protection because they lack human authorship. The decision distinguishes between the human-written text (protected) and the AI visual output (public domain), setting a major legal precedent for generative AI IP rights."
  },
  {
    id: "tech-deep-3",
    title: "Google DeepMind releases Gemini 1.5 Pro Technical Report",
    content: "Google has published the technical report for Gemini 1.5 Pro. The model features a Mixture-of-Experts (MoE) architecture and a 10M token context window. In 'Needle-in-a-Haystack' tests, it achieved 99% recall across 1M tokens. The report also details new reinforcement learning techniques used to reduce hallucinations in code generation."
  }
];

async function runTest() {
  console.log("🚀 Starting AI Pipeline Test (Stress Test Mode)...");
  console.log("Using Model: tngtech/deepseek-r1t-chimera:free");

  try {
    const completion = await openai.chat.completions.create({
      model: "tngtech/deepseek-r1t-chimera:free", 
      messages: [
        { 
            role: "user", 
            content: SYSTEM_PROMPT + "\n\nDATA TO ANALYZE:\n" + JSON.stringify(MOCK_ARTICLES) 
        },
      ],
    });

    const rawOutput = completion.choices[0].message.content;
    console.log("\n✅ RAW AI OUTPUT:");
    console.log(rawOutput);

    // 2️⃣ Improved Parsing (Finds the FIRST array valid block)
    try {
      let jsonString = rawOutput.trim();
      // Find the first '['
      const start = jsonString.indexOf('[');
      // Find the last ']'
      const end = jsonString.lastIndexOf(']');
      
      if (start !== -1 && end !== -1) {
          jsonString = jsonString.substring(start, end + 1);
          const parsed = JSON.parse(jsonString);
          console.log("\n🎯 PARSED RESULTS:");
          console.log(JSON.stringify(parsed, null, 2));
          fs.writeFileSync('test_data.json', JSON.stringify(parsed, null, 2));
      } else {
          throw new Error("No JSON array found in output");
      }
    } catch(e) {
      console.error("❌ Final JSON Parse Error:", e.message);
    }

  } catch (error) {
    console.error("\n❌ FAILED:");
    console.error(error.message);
  }
}

runTest();

